version: '2'

services:
 db:
   image: mariadb
   volumes:
     - /Users/bochuan/PycharmProjects/AuthenticationBackup:/data/db
   ports:
     - "3306:3306"
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: auth
     MYSQL_DATABASE: authentication
     MYSQL_USER: root
     MYSQL_PASSWORD: auth


 phpmyadmin:
   image: 'phpmyadmin/phpmyadmin'
   restart: always
   ports:
     - '8080:80'
   links:
     - db:mysql
   environment:
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: auth

 authentication:
   depends_on:
     - db
   build:
     context: ./
     dockerfile: Dockerfile
   container_name: authentication
   image: ms-authentication:1.0
   volumes:
     - ./:/var/www/html
   hostname: ms-authentication
   ports:
     - "5000:80"
   environment:
     MS_NAME: authentication
     DB_CONNECTION: mysql
     DB_HOST: 192.168.1.105
     DB_DATABASE: authentication
     DB_USERNAME: root
     DB_PASSWORD: auth

   networks:
     - diffusion

networks:
 diffusion:
   driver: "bridge"
