from flask_sqlalchemy import SQLAlchemy
import uuid

# Define mysql database connection string
DATABASE_URI = "mysql+mysqlconnector://root:Sci123456@localhost/UserDB"

# Initialize SQLAlchemy with no settings
db = SQLAlchemy()


# mysql-> user table
class User(db.Model):
    """
      id: auto-increment id
      public_id: an unique id to locate a user, the value will be generated by the auth service
      fname: first name
      lname: last name
      birthday: user birthday that is used to calculate the user's age
      email: unique user email
      phone: user's phone number
      address: user's address which can be null
    """
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    public_id = db.Column(db.String(50), unique=True)
    fname = db.Column(db.String(100), nullable=False)
    lname = db.Column(db.String(100), nullable=False)
    birthday = db.Column(db.Date, nullable=False)
    email = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(100), nullable=False)
    address = db.Column(db.Text(), nullable=True)

    def __repr__(self):
        return "<User {}: {}: {}: {}: {}: {}: {}: {}>".format(self.id, self.public_id, self.fname,
                                                              self.lname, self.birthday, self.email,
                                                              self.phone, self.address)


# Function that convert row to dictionary form
def row2dict(row):
    return {col.name: str(getattr(row, col.name)) for col in row.__table__.columns}


# Initial database for ticket booking service
def init_database():
    db.drop_all()
    db.create_all()
    # init_user_table()


# Populate the ticket table
def init_user_table():
    # Populate ticket table (hard coded version for testing purpose)
    db.session.add(User(public_id=str(uuid.uuid4()),
                        fname="Jennifer",
                        lname="Williams",
                        birthday="1988-05-19",
                        email="JenniferTWilliams@rhyta.com",
                        phone="209-752-1056",
                        address="1613 Freed Drive"))

    db.session.add(User(public_id=str(uuid.uuid4()),
                        fname="Carlos",
                        lname="Bartlett",
                        birthday="1978-03-29",
                        email="CarlosABartlett@jourrapide.com",
                        phone="321-328-4916",
                        address="2754 Terry Lane"))

    db.session.add(User(public_id=str(uuid.uuid4()),
                        fname="Lester",
                        lname="James",
                        birthday="1988-01-13",
                        email="LesterAJames@armyspy.com",
                        phone="337-536-9002",
                        address="2995 Sarah Drive"))

    db.session.commit()
